
trigger: 
  branches:
    include:
      - master
      - develop

  paths:
    include:
      - shared-infrastructure/RetrievedPensionDetailsQueue/*.yml
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: RetrievedPensionDetailsQueue-DEV

steps:
- task: Npm@1
  displayName: 'Install JsonLint'
  inputs:
    command: 'custom'
    customCommand: 'install jsonlint -g'

- task: CmdLine@2
  displayName: 'Echo the Agents work directory to the console'
  inputs:
    script: 'echo $(Agent.WorkFolder)'

- bash: echo This script could use $(Agent.WorkFolder)

- task: CmdLine@2
  inputs:
    script: 'jsonlint template.json'
    workingDirectory: 'shared-infrastructure/RetrievedPensionDetailsQueue'
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Pension Details Retrieved Queue ARM Template Validation'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MHPDCloudServices-DEV'
    subscriptionId: '3a9bae85-2f6e-47a1-a371-7ee3c84cf70b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mhpd-cloudservices-rg-dev'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'shared-infrastructure/RetrievedPensionDetailsQueue/template.json'
    csmParametersFile: 'shared-infrastructure/RetrievedPensionDetailsQueue/parameters.json'
    overrideParameters: '-serviceBusNamespaceName $(serviceBusNamespaceName) -serviceBusQueueName $(serviceBusQueueName)'
    deploymentMode: 'Validation'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))
  inputs:
    PathtoPublish: 'shared-infrastructure/RetrievedPensionDetailsQueue'
    ArtifactName: 'drop'
    publishLocation: 'Container'

