trigger: none
name: Github synch backend

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git config --global user.email $(user-email)
      git config --global user.name $(user-name)
      git config --global init.defaultBranch main
      git clone https://moneyandpensionsservice@dev.azure.com/moneyandpensionsservice/MaPS%20Digital/_git/mhpd-backend
      rm -rf .git
      git init
      git branch -M main
      git add -f .
      git commit -am 'Clean backend repo'
      git push -f https://$(backend-personal-access-token)@github.com/moneyadviceservice/mhpd-backend.git main
    displayName: 'Clean backend repo and push to Github'
