trigger: none
name: Github synch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git config --global user.email $(user-email)
      git config --global user.name $(user-name)
      git config --global init.defaultBranch main
      git clone https://moneyandpensionsservice@dev.azure.com/moneyandpensionsservice/MaPS%20Digital/_git/maps-apps
      rm -rf .git
      git init
      git branch -M main
      git add -f .
      git commit -am 'Clean frontend repo'
      git push -f https://$(personal-access-token)@github.com/moneyadviceservice/maps-apps.git main
    displayName: 'Clean frontend repo and push to Github'
