# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - src/IntegrationServices/CDAServiceEmulator/CDAServiceEmulator/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectsToRestore: | 
     src/IntegrationServices/CDAServiceEmulator/CDAServiceEmulator/CDAServiceEmulator.csproj
     tests/CDAServiceEmulatorUnitTests/*.csproj

steps:
- script: echo 'Starting CDA Service Emulator build pipeline'

- task: UseDotNet@2
  displayName: 'Install .NET Core 8.x'
  inputs:
    version: 8.x
    
- task: DotNetCoreCLI@2
  displayName: 'Restore projects'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: |
     '$(projectsToRestore)'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'src/IntegrationServices/CDAServiceEmulator/CDAServiceEmulator/CDAServiceEmulator.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests - $(buildConfiguration)'
  inputs:
    command: 'test'
    projects: 'tests/CDAServiceEmulatorUnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect "Code coverage" --results-directory "$(Build.SourcesDirectory)/TestResults/Coverage/"'
    publishTestResults: false

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    searchFolder: '$(Build.SourcesDirectory)/TestResults/Coverage/'

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/'

- task: DotNetCoreCLI@2
  displayName: 'Publish and zip'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/IntegrationServices/CDAServiceEmulator/CDAServiceEmulator/CDAServiceEmulator.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: echo 'Finish CDA Service Emulator build pipeline'
